package model.services;

/* ESTA É UMA INTERFACE, ELAS SÃO USADAS PARA DEFINIR OS MÉTODOS QUE UMA CLASSE VAI USAR.
 * NO CASO É NECESSÁRIO UMA CLASSE PARA IMPLEMENTAR A INTERFACE.
 * A INTERFACE É COMO SE FOSSE UM CONTRATO QUE DEFINE OS MÉTODOS QUE A CLASSE IMPLEMENTADORA DEVE EXECUTAR
 * 
 * INTERFACE É UM TIPO GENÉRICO, USADO PARA FACILITAR A MANUTENÇÃO DE CODIGO
 * AO INVÉS DE ALTERAR VÁRIOS PONTOS, PODEMOS ALTERAR APENAS A CLASSE IMPLEMENTADORA
 */

public interface TaxService {

	double tax(double amount);
}
